Repository Rafael-conquista/Goal_notes, pull requests merged in 2024-09, with the labels that each got.

#141 Responsividade
  api/controllers/Amigos_controller.py
  front/goals-notes/src/components/Style/homeStyle.css
  front/goals-notes/src/components/Style/navbar.css
  front/goals-notes/src/components/Style/perfil.css
  front/goals-notes/src/components/amigosConsult.js
  front/goals-notes/src/components/capUpdate.js
  front/goals-notes/src/components/navbar copy.js
  front/goals-notes/src/components/navbar.js
  front/goals-notes/src/components/userUpdate.js
  front/goals-notes/src/pages/perfil/perfil.js
  front/goals-notes/src/services/amigos_requests.js
  front/goals-notes/src/services/api_requests.js
  front/goals-notes/src/services/cap_requests.js
  front/goals-notes/src/services/goals_request.js
  front/goals-notes/src/services/user_requests.js
Labels: bug, enhancement

#144 Correcao dos erros
  front/goals-notes/src/components/Style/loginStyle.css
  front/goals-notes/src/components/login.js
  front/goals-notes/src/components/register.js
  front/goals-notes/src/pages/initial_page/initial_page.js
Labels: bug

#152 Ajustes layout goals
  front/goals-notes/package.json
  front/goals-notes/src/components/GoalsContainers.js
  front/goals-notes/src/components/Style/footer.css
  front/goals-notes/src/components/Style/goals_container.css
  front/goals-notes/src/components/Style/loading.css
  front/goals-notes/src/components/Style/perfil.css
  front/goals-notes/src/components/Style/store.css
  front/goals-notes/src/components/amigosConsult.js
  front/goals-notes/src/components/finishedGoals.js
  front/goals-notes/src/components/goalCreator.js
  front/goals-notes/src/components/login.js
  front/goals-notes/src/components/navbar.js
  front/goals-notes/src/components/pomodoroModal.js
  front/goals-notes/src/components/register.js
  front/goals-notes/src/components/usuarioFoto.js
  front/goals-notes/src/pages/goals/goals.js
  front/goals-notes/src/pages/perfil/perfil.js
Labels: bug, enhancement, good first issue

#153 Criando rota controller view conquistas
  api/Routes/Users.py
  api/app.py
  api/controllers/Users_controller.py
  front/goals-notes/src/App.js
  front/goals-notes/src/components/Conquista.js
  front/goals-notes/src/components/GoalsContainers.js
  front/goals-notes/src/components/Style/conquista.css
  front/goals-notes/src/components/Style/goals_container.css
  front/goals-notes/src/components/Style/store.css
  front/goals-notes/src/components/amigosConsult.js
  front/goals-notes/src/components/finishedGoals.js
  front/goals-notes/src/components/navbar.js
  front/goals-notes/src/images/capivaraAmigaDez.png
  front/goals-notes/src/images/capivaraAmigaUm.png
  front/goals-notes/src/images/capivaraTarefaDez.png
  front/goals-notes/src/images/capivaraTarefaUm.png
  front/goals-notes/src/pages/conquista/conquistaGeral.js
  front/goals-notes/src/pages/store/store.js
  front/goals-notes/src/services/user_requests.js
Labels: enhancement
