Repository Rafael-conquista/Goal_notes, pull requests merged in 2024-06, with the labels that each got.

#91 feat: Criação de método de Pomodoro em uma página
  api/docker-compose.yaml
  api/dockerfile
  api/read.me
  api/requirements.txt
  front/goals-notes/src/App.js
  front/goals-notes/src/pages/pomodoro/pomodoro.js
  front/goals-notes/src/pages/pomodoro/pomodoro.module.css
Labels: review

#92 Criando_Tela_Perfil
  api/Routes/Amigos.py
  api/app.py
  api/controllers/Amigos_controller.py
  api/controllers/Users_controller.py
  front/goals-notes/src/components/Style/perfil.css
  front/goals-notes/src/components/Style/userStyle.css
  front/goals-notes/src/components/amigosConsult.js
  front/goals-notes/src/components/capUpdate.js
  front/goals-notes/src/components/userUpdate.js
  front/goals-notes/src/pages/perfil/perfil.js
  front/goals-notes/src/services/amigos_requests.js
  front/goals-notes/src/services/cap_requests.js
  front/goals-notes/src/services/home_request.js
  front/goals-notes/src/services/user_requests.js
Labels: enhancement

#97 Ajustando erro de cadastro
  front/goals-notes/src/components/userUpdate.js
Labels: bug

#101 transforma página de pomodoro em componente de metas
  api/controllers/Goals_controller.py
  api/models/Goals_model.py
  front/goals-notes/src/App.js
  front/goals-notes/src/components/GoalsContainers.js
  front/goals-notes/src/components/Style/pomodoro.module.css
  front/goals-notes/src/components/pomodoroModal.js
  front/goals-notes/src/pages/pomodoro/pomodoro.js
  front/goals-notes/src/services/goals_request.js
Labels: in progress
